<?php
$active='anuncie'; require_once __DIR__.'/site_helpers.php'; $msg='';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST' && ($_POST['form_type']??'')==='ad'){
  $orders=tvs_read_admin_json('anuncios_pedidos.json');
  $orders[]=['id'=>uniqid('ad_'),'company'=>tvs_safe_text($_POST['company']??''),'responsible'=>tvs_safe_text($_POST['responsible']??''),'whatsapp'=>tvs_safe_text($_POST['whatsapp']??''),'email'=>tvs_safe_text($_POST['email']??''),'plan'=>tvs_safe_text($_POST['plan']??''),'placement'=>tvs_safe_text($_POST['placement']??''),'period'=>tvs_safe_text($_POST['period']??''),'link'=>tvs_safe_text($_POST['link']??''),'message'=>tvs_safe_text($_POST['message']??''),'banner'=>tvs_upload_public_file('banner','anuncios'),'receipt'=>tvs_upload_public_file('receipt','comprovantes'),'status'=>'recebido','created_at'=>date('c')];
  tvs_save_admin_json('anuncios_pedidos.json',$orders); $msg='Solicitação enviada. A equipe comercial fará a conferência do pagamento e a aprovação do material publicitário.';
}
function h($v){return htmlspecialchars((string)$v);} ?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Anuncie na TV Sumaré | Publicidade em Sumaré e Região</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/style.css"></head><body><?php include 'header.php'; ?><main class="container page-shell">
<div class="page-title"><span>PUBLICIDADE • TV SUMARÉ</span><h1>Anuncie na TV Sumaré</h1><p><strong>Coloque sua empresa em destaque para Sumaré e região.</strong> Divulgue sua marca nos espaços comerciais da TV Sumaré com presença no Guia Comercial, banners publicitários e campanhas regionais.</p></div>
<div class="ad-banner" style="margin-bottom:24px"><strong>Planos para anunciantes</strong><br><span>Você está contratando divulgação e espaço publicitário na TV Sumaré. Estes planos não correspondem a assinatura ou acesso ao aplicativo/plataforma TV Sumaré.</span></div>
<?php if($msg): ?><div class="ad-banner"><strong><?=h($msg)?></strong></div><?php endif; ?>
<div class="pricing-grid">
<article class="price-card"><span class="plan-badge">Presença local</span><h2>Presença no Guia Comercial</h2><p class="price">R$ 149<span>/mês</span></p><ul><li>Cadastro da empresa no Guia Comercial</li><li>Botão para contato via WhatsApp</li><li>Endereço e redes sociais</li></ul><a class="btn btn-outline" href="guia.php">Cadastrar minha empresa</a></article>
<article class="price-card featured"><span class="plan-badge">Mais visibilidade</span><h2>Publicidade em Banner</h2><p class="price">R$ 299<span>/mês</span></p><ul><li>Banner publicitário rotativo</li><li>Link para WhatsApp ou site</li><li>Material sujeito à aprovação editorial/comercial</li></ul><a class="btn btn-primary" href="#contratar">Anunciar na TV Sumaré</a></article>
<article class="price-card"><span class="plan-badge">Campanha completa</span><h2>Campanha Publicitária Regional</h2><p class="price">R$ 599<span>/mês</span></p><ul><li>Exposição na Home e em notícias</li><li>Conteúdo publieditorial</li><li>Divulgação em redes sociais</li></ul><a class="btn btn-outline" href="#contratar">Solicitar proposta comercial</a></article>
</div>
<section class="box" id="contratar" style="margin-top:30px"><span class="plan-badge">PARA ANUNCIANTES</span><h2>Solicitar espaço publicitário</h2><p>Preencha os dados da sua empresa e escolha onde deseja anunciar. Nossa equipe fará a conferência do material e retornará sobre a publicação.</p><form method="post" enctype="multipart/form-data" class="filter-bar" style="display:grid;grid-template-columns:repeat(2,1fr);gap:14px"><input type="hidden" name="form_type" value="ad"><input name="company" required placeholder="Nome da empresa"><input name="responsible" required placeholder="Responsável"><input name="whatsapp" required placeholder="WhatsApp"><input name="email" type="email" placeholder="E-mail"><select name="plan"><option>Publicidade em Banner — R$ 299/mês</option><option>Campanha Publicitária Regional — R$ 599/mês</option><option>Publieditorial</option><option>Outro formato publicitário</option></select><select name="placement"><option>Home</option><option>Notícias</option><option>Guia Comercial</option><option>Ao Vivo</option><option>Banner lateral</option></select><input name="period" placeholder="Período desejado da campanha"><input name="link" placeholder="Link de destino (site, WhatsApp ou rede social)"><textarea name="message" placeholder="Conte sobre sua campanha, oferta ou objetivo de divulgação" style="grid-column:1/-1"></textarea><label>Banner/arte <input type="file" name="banner" accept="image/*,application/pdf"></label><label>Comprovante PIX <input type="file" name="receipt" accept="image/*,application/pdf"></label><button class="btn btn-primary" type="submit">Enviar solicitação para aprovação</button></form></section>
<section class="box" style="margin-top:24px"><h2>Novos formatos em preparação</h2><p>A TV Sumaré está ampliando suas possibilidades comerciais. A estrutura será preparada para receber também vídeo patrocinado, patrocínio do Boletim TV Sumaré e patrocínio de transmissões ao vivo.</p></section>
</main><?php include 'rodape.php'; ?></body></html>
