<?php $active='eleicoes'; require_once __DIR__.'/includes/elections_2026.php'; ?><!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Eleições 2026 | TV Sumaré</title><link rel="stylesheet" href="/assets/style.css">
<style>
.election-page{max-width:1120px;margin:32px auto;padding:0 20px;color:#10213b}.election-page h1{font-size:clamp(28px,4vw,42px);margin:12px 0}.election-page p{line-height:1.6}.election-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px;margin:28px 0}.race{border:1px solid #d4deeb;border-radius:16px;padding:24px;background:#fff}.race:first-child{grid-column:1/-1}.race h2{font-size:22px;margin-top:0}.race ul{list-style:none;padding:0}.candidate{padding:16px 0;border-bottom:1px solid #e2e8f0}.candidate-line{display:flex;justify-content:space-between;gap:12px;font-weight:700}.candidate small{display:block;margin:6px 0;color:#475569}.race progress{width:100%;height:10px;accent-color:#174ea6}.race time{display:block;font-size:13px;margin-top:16px;color:#475569}.status{padding:12px;background:#eff4fc;border-radius:8px}.warning{background:#fff3cd;color:#614700}.election-page a{color:#174ea6;text-decoration:underline}.election-page a:focus-visible{outline:3px solid #174ea6;outline-offset:4px}@media(max-width:850px){.election-grid{grid-template-columns:1fr}}
 .projection-inside{background:#dcfce7;color:#14532d} .election-layout{display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:24px;align-items:start}.election-sidebar{position:sticky;top:20px;border:1px solid #d4deeb;border-radius:16px;background:#fff;padding:20px;margin-top:28px;max-height:85vh;overflow:auto}.election-sidebar h2{font-size:22px;margin-top:0}.election-sidebar summary{cursor:pointer;font-weight:700;padding:12px 0}.sidebar-candidate{border-top:1px solid #e2e8f0;padding:12px 0}.sidebar-candidate strong{display:block}.sidebar-candidate p{font-size:14px;margin:6px 0}.election-sidebar select{width:100%;padding:10px;border:1px solid #94a3b8;border-radius:8px}.election-layout .election-grid{grid-template-columns:1fr}.election-page{max-width:1360px}@media(max-width:1050px){.election-layout{grid-template-columns:1fr}.election-sidebar{position:static;max-height:none;order:-1;margin-top:20px}}\n</style></head><body><?php include __DIR__.'/header.php'; ?>
<main class="election-page"><a href="/">← TV Sumaré</a><h1>Eleições 2026 — Apuração oficial</h1>
<p>1º turno • 4 de outubro de 2026. Presidente: resultado geral do Brasil. Demais cargos: apuração por estado.</p>
<p>Fonte: Tribunal Superior Eleitoral. Atualização automática a cada 30 segundos. Resultados parciais podem mudar.</p>
<p><label for="election-state">Estado dos demais cargos</label><br><select id="election-state" style="padding:12px;max-width:480px;width:100%;border:1px solid #94a3b8;border-radius:8px"><?php foreach(tvs_election_states() as $uf=>$name): ?><option value="<?= htmlspecialchars($uf,ENT_QUOTES,'UTF-8') ?>" <?= $uf==='sp'?'selected':'' ?>><?= htmlspecialchars($name,ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></p>
<p><label for="candidate-search">Buscar candidatura por nome, número ou partido</label><br><input id="candidate-search" type="search" placeholder="Digite para buscar" style="padding:12px;width:100%;max-width:480px;border:1px solid #94a3b8;border-radius:8px"></p><p>Listas ordenadas por votos. Exibimos até 50 candidaturas por cargo; use a busca para localizar outras. Para deputados, a votação individual não determina sozinha a eleição: a distribuição de vagas também depende das regras proporcionais.</p>
<div id="election-status" role="status">Consultando a fonte oficial…</div><div class="election-layout"><div id="election-grid" class="election-grid"></div><aside class="election-sidebar" aria-label="Situação dos candidatos"><details id="candidate-panel" open><summary>Situação dos candidatos</summary><label for="sidebar-office">Cargo</label><select id="sidebar-office"><option value="deputado-federal">Deputado federal</option><option value="deputado-estadual">Deputado estadual / distrital</option><option value="presidente">Presidente</option><option value="governador">Governador</option><option value="senador">Senador</option></select><div id="candidate-indicators"></div></details></aside></div>
<p>Os percentuais são os informados pelo TSE. No Senado, cada eleitor pode votar em dois candidatos; o percentual não representa a proporção de eleitores.</p>
<p><a href="https://resultados.tse.jus.br/oficial/app/index.html" target="_blank" rel="noopener noreferrer">Consultar resultados no TSE</a></p>
<noscript>Ative o JavaScript para acompanhar os dados, ou consulte o site oficial do TSE pelo link acima.</noscript>
</main><script>
(()=>{const grid=document.getElementById('election-grid'),status=document.getElementById('election-status'),search=document.getElementById('candidate-search');let latest=null;let requestId=0,activeController=null,nextTimer=null;const state=document.getElementById('election-state');
state.addEventListener('change',()=>{clearTimeout(nextTimer);if(activeController)activeController.abort();latest=null;grid.replaceChildren();sidebar.replaceChildren();status.textContent='Consultando '+state.options[state.selectedIndex].text+'…';refresh();});
const sidebar=document.getElementById('candidate-indicators'),office=document.getElementById('sidebar-office');office.addEventListener('change',()=>{if(latest)renderSidebar(latest)});if(matchMedia('(max-width:1050px)').matches)document.getElementById('candidate-panel').open=false;
search.addEventListener('input',()=>{if(latest)render(latest)});
const normalize=value=>String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const number=new Intl.NumberFormat('pt-BR'),percent=new Intl.NumberFormat('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
function el(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node}
function renderSidebar(data){
sidebar.replaceChildren();const index={'presidente':0,'governador':1,'senador':2,'deputado-federal':3,'deputado-estadual':4}[office.value],race=data.races[index];if(!race||race.unavailable){sidebar.append(el('p','Aguardando dados oficiais para este cargo.','status warning'));return;}
sidebar.append(el('h2',race.title),el('p',percent.format(race.sections)+'% das seções totalizadas'));
if(race.stale)sidebar.append(el('p','Dados atrasados: consulte o horário da fonte.','status warning'));
if(race.proportional){sidebar.append(el('p','Projeção parcial TV Sumaré — cálculo próprio com os votos já apurados. Não antecipa os votos restantes e não confirma eleição.','status'));if(race.projection&&!race.projection.available)sidebar.append(el('p','Projeção indefinida: '+race.projection.reason,'status warning'));sidebar.append(el('p','Quociente eleitoral '+(race.final?'oficial':'parcial')+': '+(race.electoral_quotient>0?number.format(race.electoral_quotient)+' votos':'ainda indisponível')));sidebar.append(el('p','Vagas do cargo: '+(race.seats??'indisponível')));sidebar.append(el('p','A posição por votos não garante eleição. Sobras, requisitos legais e decisões judiciais também influenciam.'))}
const query=normalize(search.value.trim()),filtered=race.candidates.filter(c=>!query||normalize(c.name+' '+c.number+' '+c.party+' '+(c.group_name||'')).includes(query));
const showingSeats=!query&&race.proportional&&race.projection?.available;
const visible=showingSeats?filtered.filter(c=>c.projection?.status==='inside'):filtered.slice(0,race.proportional?(race.seats||50):50);
if(showingSeats)sidebar.append(el('p','Exibindo as '+visible.length+' vagas na projeção atual, de '+race.seats+' informadas pelo TSE. Use a busca para consultar outras candidaturas.'));
for(const candidate of visible){const row=el('div',undefined,'sidebar-candidate');row.append(el('strong',candidate.name),el('p',candidate.party+' • '+candidate.number+' • '+number.format(candidate.votes)+' votos'));
if(race.proportional){row.append(el('p',candidate.group_name||candidate.party));if(candidate.group_rank)row.append(el('p','Posição no grupo: '+candidate.group_rank+'º'+(candidate.group_tied?' (empatada por votos)':'')));row.append(el('p','Vagas do grupo informadas pelo TSE: '+(candidate.group_seats??'indisponível')))}
if(race.proportional){
const projected=candidate.projection?.status,label=projected==='inside'?'Dentro das vagas na projeção atual':projected==='outside'?'Fora das vagas na projeção atual':'Indefinido na projeção atual';
row.append(el('p',label,projected==='inside'?'status projection-inside':projected==='outside'?'status':'status warning'));
if(candidate.projected_group_seats!==null&&candidate.projected_group_seats!==undefined)row.append(el('p','Vagas do grupo no cálculo TV Sumaré: '+candidate.projected_group_seats));
if(candidate.projection?.reason)row.append(el('p',candidate.projection.reason));
}
row.append(el('p',candidate.status?'Situação oficial: '+candidate.status:'Eleição individual ainda não confirmada pelo TSE.','status'));sidebar.append(row)}
if(!visible.length)sidebar.append(el('p','Nenhuma candidatura corresponde à busca.'));if(!showingSeats&&filtered.length>visible.length)sidebar.append(el('p','Mostrando '+visible.length+' candidaturas. Refine a busca para localizar outras.'));sidebar.append(el('p','Última atualização: '+new Date(race.updated_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})));
}
function render(data){renderSidebar(data);latest=data;const query=normalize(search.value.trim());const fragment=document.createDocumentFragment();
for(const race of data.races){const card=el('section',undefined,'race');card.append(el('h2',race.title));
if(race.unavailable){card.append(el('p',race.reason==='waiting'?'O TSE ainda informa totalização não iniciada. Aguardando a primeira atualização.':'Aguardando dados oficiais. A fonte ainda não pôde ser consultada.','status warning'));}
else{card.append(el('p',percent.format(race.sections)+'% das seções totalizadas'));const progress=el('progress');progress.max=100;progress.value=race.sections;progress.setAttribute('aria-label','Seções totalizadas');card.append(progress);
if(race.stale)card.append(el('p','Atualização atrasada. Exibindo a última leitura válida.','status warning'));
else card.append(el('p',race.final?'Totalização final informada pelo TSE':'Apuração parcial','status'));
const list=el('ul');for(const candidate of race.candidates.filter(c=>!query||normalize(c.name+' '+c.number+' '+c.party).includes(query)).slice(0,50)){const row=el('li',undefined,'candidate'),line=el('div',undefined,'candidate-line');line.append(el('span',candidate.name),el('span',percent.format(candidate.percent)+'%'));row.append(line,el('small',candidate.party+' • '+candidate.number+' • '+number.format(candidate.votes)+' votos'));if(candidate.status)row.append(el('small','Situação no TSE: '+candidate.status));list.append(row)}card.append(list);
const time=el('time','Arquivo do TSE: '+new Date(race.updated_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})+' (Brasília)');time.dateTime=race.updated_at;card.append(time);}
fragment.append(card)}grid.replaceChildren(fragment);status.textContent='';}
async function refresh(){if(document.hidden){nextTimer=setTimeout(refresh,30000);return}const id=++requestId,controller=new AbortController();activeController=controller;const timer=setTimeout(()=>controller.abort(),35000);try{const response=await fetch('/eleicoes-2026-dados.php?uf='+encodeURIComponent(state.value),{signal:controller.signal,cache:'no-store'});if(!response.ok)throw new Error();const data=await response.json();if(!Array.isArray(data.races))throw new Error();if(id===requestId)render(data);}catch(error){if(id===requestId)status.textContent='Não foi possível atualizar agora. Nova tentativa em 30 segundos; confira o horário dos dados abaixo.';}finally{clearTimeout(timer);if(id===requestId)nextTimer=setTimeout(refresh,30000)}}refresh();})();
</script></body></html>
