<?php
$path='/var/www/html/admin/reporter-ia.php';
$code=file_get_contents($path);
if($code===false){fwrite(STDERR,"Reporter IA não encontrado\n");exit(1);}
function rq_replace(&$code,$old,$new,$label){$count=substr_count($code,$old);if($count!==1){fwrite(STDERR,"{$label}: trecho esperado count={$count}; abortando\n");exit(2);} $code=str_replace($old,$new,$code);}

rq_replace($code,
"function rpia_friendly_error(\$context,\$detail=''){ rpia_log_technical_error(\$context,\$detail); \$map=['test'=>'Não foi possível validar a conexão com o provedor de vídeo agora. Tente novamente em alguns instantes.','send'=>'Não foi possível enviar este vídeo para processamento agora. O roteiro foi preservado e pode ser reenviado.','check'=>'Não foi possível atualizar o processamento agora. O estado anterior foi preservado.','failed'=>'O provedor não conseguiu concluir este vídeo. Os detalhes técnicos foram registrados para diagnóstico.']; return \$map[\$context]??'Não foi possível concluir esta operação agora. Os detalhes técnicos foram registrados.'; }",
"function rpia_friendly_error(\$context,\$detail=''){ rpia_log_technical_error(\$context,\$detail); \$map=['test'=>'Não foi possível validar a conexão com o provedor de vídeo agora. Tente novamente em alguns instantes.','send'=>'Não foi possível enviar este vídeo para processamento agora. O roteiro foi preservado e pode ser reenviado.','check'=>'Não foi possível atualizar o processamento agora. O estado anterior foi preservado.','failed'=>'O provedor não conseguiu concluir este vídeo. Os detalhes técnicos foram registrados para diagnóstico.','credits'=>'Repórter IA indisponível temporariamente — franquia/API sem saldo. Nenhum novo vídeo será enviado até a regularização.']; return \$map[\$context]??'Não foi possível concluir esta operação agora. Os detalhes técnicos foram registrados.'; }\nfunction rpia_is_credit_error(\$detail){ \$d=strtolower((string)\$detail); return strpos(\$d,'insufficient credit')!==false || strpos(\$d,'api credits')!==false || strpos(\$d,'requires \'api\' credits')!==false; }\nfunction rpia_provider_blocked(\$cfg){ return !empty(\$cfg['heygen_send_blocked']); }\nfunction rpia_job_state(\$j){ \$s=strtolower((string)(\$j['status']??'roteiro_pronto')); if(in_array(\$s,['cancelado','cancelled','canceled'],true)) return 'cancelled'; if(in_array(\$s,['heygen_falhou','failed','falhou','erro'],true)) return 'failed'; if(in_array(\$s,['video_pronto','completed','complete','ready','pronto'],true)||!empty(\$j['video_url'])||!empty(\$j['captioned_video_url'])) return 'completed'; if(in_array(\$s,['heygen_agente_processando','processing','enviado','submitted'],true)||!empty(\$j['heygen_session_id'])||!empty(\$j['heygen_video_id'])) return 'processing'; if(in_array(\$s,['publicado','published'],true)) return 'published'; return 'ready'; }\nfunction rpia_state_label(\$state){ return ['ready'=>'Roteiro pronto','processing'=>'Processando','completed'=>'Vídeo pronto','failed'=>'Falhou','cancelled'=>'Cancelado','published'=>'Publicado'][\$state]??'Aguardando'; }",
'Reporter state helpers');

rq_replace($code,
"if(\$action==='send_heygen'){ \$idx=null; [\$job,\$jobs]=rpia_find_videojob(\$_POST['job_id']??'',\$idx); if(!\$job) \$err='Roteiro não encontrado.'; else { \$r=rpia_heygen_create(\$job,\$cfg); if(!\$r['ok']) { \$jobs[\$idx]['status']='heygen_falhou'; \$jobs[\$idx]['technical_error']=substr((string)(\$r['error']??''),0,1200); \$jobs[\$idx]['updated_at']=date('c'); rpia_write('videos_ia.json',\$jobs); \$err=rpia_friendly_error('send',\$r['error']??''); } else {",
"if(\$action==='send_heygen'){ \$idx=null; [\$job,\$jobs]=rpia_find_videojob(\$_POST['job_id']??'',\$idx); if(!\$job) \$err='Roteiro não encontrado.'; elseif(rpia_provider_blocked(\$cfg)) \$err=rpia_friendly_error('credits','provider_blocked'); elseif(rpia_job_state(\$job)!=='ready' || !empty(\$job['heygen_session_id']) || !empty(\$job['heygen_video_id'])) \$err='Este roteiro já foi enviado ou não está em estado válido para nova geração.'; else { \$jobs[\$idx]['send_lock_at']=date('c'); \$jobs[\$idx]['status']='enviado'; rpia_write('videos_ia.json',\$jobs); \$r=rpia_heygen_create(\$job,\$cfg); if(!\$r['ok']) { \$detail=(string)(\$r['error']??''); \$jobs[\$idx]['status']='heygen_falhou'; \$jobs[\$idx]['technical_error']=substr(\$detail,0,1200); \$jobs[\$idx]['updated_at']=date('c'); unset(\$jobs[\$idx]['send_lock_at']); if(rpia_is_credit_error(\$detail)){ \$cfg['heygen_send_blocked']='1'; \$cfg['heygen_send_blocked_reason']='credits'; \$cfg['heygen_send_blocked_at']=date('c'); rpia_config_save(\$cfg); \$err=rpia_friendly_error('credits',\$detail); } else \$err=rpia_friendly_error('send',\$detail); rpia_write('videos_ia.json',\$jobs); } else {",
'Reporter idempotent send');

rq_replace($code,
"\$jobs[\$idx]['status']='heygen_agente_processando'; \$jobs[\$idx]['updated_at']=date('c'); rpia_write('videos_ia.json',\$jobs); \$msg='Agente de Vídeo HeyGen criado.",
"\$jobs[\$idx]['status']='heygen_agente_processando'; unset(\$jobs[\$idx]['send_lock_at']); \$jobs[\$idx]['updated_at']=date('c'); rpia_write('videos_ia.json',\$jobs); \$msg='Agente de Vídeo HeyGen criado.",
'Reporter unlock after send');

rq_replace($code,
"if(\$action==='publish_video'){ \$idx=null; [\$job,\$jobs]=rpia_find_videojob(\$_POST['job_id']??'',\$idx); if(!\$job || (empty(\$job['video_url']) && empty(\$job['captioned_video_url']))) \$err='Vídeo ainda não possui URL pronta.'; else { rpia_publish_video(\$job); \$jobs[\$idx]['status']='publicado'; \$jobs[\$idx]['published_at']=date('c'); rpia_write('videos_ia.json',\$jobs); \$msg='Vídeo publicado no TV Sumaré Play.'; } }",
"if(\$action==='publish_video'){ \$idx=null; [\$job,\$jobs]=rpia_find_videojob(\$_POST['job_id']??'',\$idx); if(!\$job || rpia_job_state(\$job)!=='completed' || (empty(\$job['video_url']) && empty(\$job['captioned_video_url']))) \$err='Vídeo ainda não está pronto para publicação.'; else { rpia_publish_video(\$job); \$jobs[\$idx]['status']='publicado'; \$jobs[\$idx]['published_at']=date('c'); rpia_write('videos_ia.json',\$jobs); \$msg='Vídeo publicado no TV Sumaré Play.'; } }\n  if(\$action==='archive_job'){ \$idx=null; [\$job,\$jobs]=rpia_find_videojob(\$_POST['job_id']??'',\$idx); if(!\$job) \$err='Item não encontrado.'; elseif(!in_array(rpia_job_state(\$job),['failed','cancelled','published'],true)) \$err='Somente itens concluídos, cancelados ou com falha podem ser arquivados.'; else { \$jobs[\$idx]['archived_at']=date('c'); \$jobs[\$idx]['archived']='1'; rpia_write('videos_ia.json',\$jobs); \$msg='Item movido para o histórico.'; } }\n  if(\$action==='release_provider_block'){ \$cfg['heygen_send_blocked']='0'; \$cfg['heygen_send_blocked_reason']=''; \$cfg['heygen_send_blocked_released_at']=date('c'); rpia_config_save(\$cfg); \$msg='Bloqueio de envio removido. O próximo envio deverá ser feito somente após confirmar a regularização da franquia/API.'; }",
'Reporter actions');

rq_replace($code,
"\$news=rpia_read('noticias.json'); usort(\$news,function(\$a,\$b){ return strcmp(\$b['published_at']??\$b['created_at']??'', \$a['published_at']??\$a['created_at']??''); }); \$news=array_slice(\$news,0,30); \$jobs=rpia_read('videos_ia.json'); \$callbackUrl=",
"\$news=rpia_read('noticias.json'); usort(\$news,function(\$a,\$b){ return strcmp(\$b['published_at']??\$b['created_at']??'', \$a['published_at']??\$a['created_at']??''); }); \$news=array_slice(\$news,0,30); \$jobs=rpia_read('videos_ia.json'); \$activeJobs=array_values(array_filter(\$jobs,function(\$j){ return empty(\$j['archived']) && !in_array(rpia_job_state(\$j),['cancelled','failed','published'],true); })); \$historyJobs=array_values(array_filter(\$jobs,function(\$j){ return !empty(\$j['archived']) || in_array(rpia_job_state(\$j),['cancelled','failed','published'],true); })); \$callbackUrl=",
'Reporter queue split');

$start='<section class="box"><h2>Fila de vídeos IA</h2><?php foreach($jobs as $j):';
$pos=strpos($code,$start);
if($pos===false){fwrite(STDERR,"Reporter queue UI start não encontrado\n");exit(3);}
$end='</section></div></main></div></body></html>';
$endPos=strpos($code,$end,$pos);
if($endPos===false){fwrite(STDERR,"Reporter queue UI end não encontrado\n");exit(4);}
$newUi=<<<'HTML'
<section class="box"><div class="top"><div><h2>Fila operacional de vídeos IA</h2><p class="mini muted">Roteiro pronto → envio → processamento → vídeo pronto → publicação. Cancelados, falhas e publicados ficam no histórico.</p></div></div>
<?php if(rpia_provider_blocked($cfg)): ?><div class="notice error"><strong>Repórter IA indisponível temporariamente — franquia/API sem saldo.</strong><br>Nenhum novo vídeo será enviado até a regularização. Os roteiros e vídeos existentes permanecem preservados.<form method="post" style="margin-top:10px" onsubmit="return confirm('Remover o bloqueio somente depois de confirmar a regularização da franquia/API?')"><?=tvs_csrf_field()?><input type="hidden" name="action" value="release_provider_block"><button class="btn secondary">Liberar envio após regularização</button></form></div><?php endif; ?>
<?php if(!$activeJobs): ?><p class="muted">Nenhum item exige ação operacional agora.</p><?php endif; ?>
<?php foreach($activeJobs as $j): $state=rpia_job_state($j); $ready=$state==='completed'; ?><article class="job"><div class="top"><div><span class="pill <?=$state==='completed'?'ok':'warn'?>"><?=rpia_h(rpia_state_label($state))?></span><span class="pill"><?=rpia_h($j['category']??'Giro da Região')?></span><h3><?=rpia_h($j['title']??'Vídeo TV Sumaré')?></h3><p class="mini muted"><?=rpia_h($j['created_at']??'')?><?php if(!empty($j['boletim'])): ?> • <?=rpia_h($j['presenter_name']??'Boletim')?><?php endif; ?></p></div><div class="actions"><?php if($state==='ready' && !rpia_provider_blocked($cfg)): ?><form method="post"><?=tvs_csrf_field()?><input type="hidden" name="action" value="send_heygen"><input type="hidden" name="job_id" value="<?=rpia_h($j['id']??'')?>"><button class="btn orange">Enviar para geração</button></form><?php elseif($state==='processing'): ?><form method="post"><?=tvs_csrf_field()?><input type="hidden" name="action" value="check_heygen"><input type="hidden" name="job_id" value="<?=rpia_h($j['id']??'')?>"><button class="btn secondary">Atualizar status</button></form><?php elseif($state==='completed'): ?><?php if(!empty($j['video_url'])||!empty($j['captioned_video_url'])): ?><a class="btn secondary" target="_blank" rel="noopener" href="<?=rpia_h($j['captioned_video_url']??$j['video_url'])?>">Abrir vídeo</a><?php endif; ?><form method="post"><?=tvs_csrf_field()?><input type="hidden" name="action" value="publish_video"><input type="hidden" name="job_id" value="<?=rpia_h($j['id']??'')?>"><button class="btn">Publicar no Play</button></form><?php endif; ?></div></div><details><summary>Ver roteiro e detalhes técnicos</summary><form method="post" style="margin-top:10px"><?=tvs_csrf_field()?><input type="hidden" name="action" value="update_script"><input type="hidden" name="job_id" value="<?=rpia_h($j['id']??'')?>"><textarea name="script"><?=rpia_h($j['script']??'')?></textarea><?php if($state==='ready'): ?><button class="btn secondary">Salvar roteiro</button><?php endif; ?></form><p class="mini muted">Sessão: <?=rpia_h($j['heygen_session_id']??'—')?> • Vídeo: <?=rpia_h($j['heygen_video_id']??'—')?></p></details></article><?php endforeach; ?>
<details style="margin-top:16px"><summary><strong>Histórico / falhas / cancelados (<?=count($historyJobs)?>)</strong></summary><?php foreach($historyJobs as $j): $state=rpia_job_state($j); ?><article class="job"><span class="pill warn"><?=rpia_h(rpia_state_label($state))?></span><h3><?=rpia_h($j['title']??'Vídeo TV Sumaré')?></h3><?php if($state==='failed'): ?><p class="mini">Não foi possível concluir este vídeo. O detalhe técnico permanece registrado internamente.</p><?php endif; ?><div class="actions"><?php if(empty($j['archived'])): ?><form method="post"><?=tvs_csrf_field()?><input type="hidden" name="action" value="archive_job"><input type="hidden" name="job_id" value="<?=rpia_h($j['id']??'')?>"><button class="btn secondary">Arquivar</button></form><?php endif; ?></div><details><summary>Detalhes</summary><p class="mini muted">Status interno: <?=rpia_h($j['status']??'')?> • Sessão: <?=rpia_h($j['heygen_session_id']??'—')?> • Vídeo: <?=rpia_h($j['heygen_video_id']??'—')?></p></details></article><?php endforeach; ?></details></section>
HTML;
$code=substr($code,0,$pos).$newUi.$end.substr($code,$endPos+strlen($end));

if(file_put_contents($path,$code)===false){fwrite(STDERR,"Falha ao gravar Reporter IA\n");exit(5);} echo "REPORTER_QUEUE_HARDENING_APPLIED=SIM\n";
