<?php
$path='/var/www/html/admin/boletim-ia.php';
$code=file_get_contents($path);
if($code===false){fwrite(STDERR,"Boletim IA não encontrado\n");exit(1);}
$old="function bia_pick_distinct(\$news,\$jobs,\$quantity,\$preferredId=''){ \$quantity=max(1,min(10,(int)\$quantity)); \$recent=bia_recent_news_ids(\$jobs,30); \$picked=[]; if(\$preferredId!==''){ \$p=bia_find_news(\$news,\$preferredId); if(\$p) \$picked[]=\$p; } foreach(\$news as \$n){ if(count(\$picked)>=\$quantity) break; \$id=(string)(\$n['id']??''); if(\$id==='' || in_array(\$id,array_map(fn(\$x)=>(string)(\$x['id']??''),\$picked),true)) continue; if(in_array(\$id,\$recent,true) && count(\$news)>\$quantity) continue; \$picked[]=\$n; } if(count(\$picked)<\$quantity){ foreach(\$news as \$n){ if(count(\$picked)>=\$quantity) break; \$id=(string)(\$n['id']??''); if(\$id!=='' && !in_array(\$id,array_map(fn(\$x)=>(string)(\$x['id']??''),\$picked),true)) \$picked[]=\$n; } } return \$picked; }";
$new="function bia_news_bucket(\$n){ \$text=mb_strtolower(bia_clean((\$n['category']??'').' '.(\$n['title']??'').' '.(\$n['summary']??'')),'UTF-8'); if(preg_match('~\\b(emprego|vaga|concurso|curso|oportunidade|edital|servi[cç]o|sa[uú]de|tr[aâ]nsito|transporte|prefeitura|educa[cç][aã]o|seguran[cç]a|pol[ií]cia)\\b~u',\$text)) return 'servico'; if(preg_match('~\\b(cultura|evento|agenda|show|festival|turismo|gastronomia|lazer|teatro|m[uú]sica|exposi[cç][aã]o|feira|cinema|esporte)\\b~u',\$text)) return 'cultura'; return 'noticia'; }\nfunction bia_pick_distinct(\$news,\$jobs,\$quantity,\$preferredId=''){ \$quantity=max(1,min(10,(int)\$quantity)); \$recent=bia_recent_news_ids(\$jobs,30); \$picked=[]; \$usedBuckets=[]; if(\$preferredId!==''){ \$p=bia_find_news(\$news,\$preferredId); if(\$p){ \$picked[]=\$p; \$usedBuckets[]=bia_news_bucket(\$p); } } foreach([true,false] as \$preferNewBucket){ foreach(\$news as \$n){ if(count(\$picked)>=\$quantity) break 2; \$id=(string)(\$n['id']??''); if(\$id==='' || in_array(\$id,array_map(fn(\$x)=>(string)(\$x['id']??''),\$picked),true)) continue; if(in_array(\$id,\$recent,true) && count(\$news)>\$quantity) continue; \$bucket=bia_news_bucket(\$n); if(\$preferNewBucket && in_array(\$bucket,\$usedBuckets,true)) continue; \$picked[]=\$n; \$usedBuckets[]=\$bucket; } } if(count(\$picked)<\$quantity){ foreach(\$news as \$n){ if(count(\$picked)>=\$quantity) break; \$id=(string)(\$n['id']??''); if(\$id!=='' && !in_array(\$id,array_map(fn(\$x)=>(string)(\$x['id']??''),\$picked),true)) \$picked[]=\$n; } } return \$picked; }";
$count=substr_count($code,$old);
if($count!==1){fwrite(STDERR,"Boletim diversity: trecho esperado count={$count}; abortando\n");exit(2);}
$code=str_replace($old,$new,$code);
if(file_put_contents($path,$code)===false){fwrite(STDERR,"Falha ao gravar Boletim IA\n");exit(3);}
echo "BOLETIM_DIVERSITY_HARDENING_APPLIED=SIM\n";
