<?php
$reporter='/var/www/html/admin/reporter-ia.php';
$code=file_get_contents($reporter);
if($code===false){fwrite(STDERR,"Reporter IA não encontrado\n");exit(1);}
function hum_patch(&$code,$old,$new,$label){$n=substr_count($code,$old);if($n!==1){fwrite(STDERR,"{$label}: trecho esperado count={$n}; abortando\n");exit(2);} $code=str_replace($old,$new,$code);}

hum_patch($code,
"function rpia_job_orientation(\$job,\$cfg){ \$v=trim((string)(\$job['orientation']??'')); if(in_array(\$v,['landscape','portrait'],true)) return \$v; \$v=trim((string)(\$cfg['heygen_orientation']??'landscape')); return in_array(\$v,['landscape','portrait'],true)?\$v:'landscape'; }",
"function rpia_job_orientation(\$job,\$cfg){ \$v=trim((string)(\$job['orientation']??'')); if(in_array(\$v,['landscape','portrait'],true)) return \$v; \$v=trim((string)(\$cfg['heygen_orientation']??'landscape')); return in_array(\$v,['landscape','portrait'],true)?\$v:'landscape'; }\nfunction rpia_presentation_profile(\$job){ \$text=tvs_lower(tvs_clean_text((\$job['category']??'').' '.(\$job['title']??'').' '.(\$job['city']??''))); if(preg_match('~\\b(cultura|evento|agenda|show|festival|turismo|gastronomia|lazer|teatro|musica|música|feira|cinema|esporte)\\b~u',\$text)) return ['id'=>'cultura','label'=>'Cultura & Agenda','direction'=>'mais leve, caloroso e espontâneo, com sorriso sutil quando adequado e energia positiva sem exagero']; if(preg_match('~\\b(emprego|vaga|servico|serviço|saude|saúde|transito|trânsito|educacao|educação|prefeitura|edital|alerta|utilidade)\\b~u',\$text)) return ['id'=>'servico','label'=>'Serviço & Utilidade','direction'=>'claro, próximo e objetivo, com ritmo calmo, pequenas pausas e ênfase natural nas informações práticas']; if(preg_match('~\\b(seguranca|segurança|policia|polícia|acidente|crime|morte|investigacao|investigação)\\b~u',\$text)) return ['id'=>'jornalistico','label'=>'Jornalístico','direction'=>'sério e humano, expressão contida, postura respeitosa, ritmo seguro e sem dramatização']; if(!empty(\$job['boletim'])) return ['id'=>'dinamico','label'=>'Dinâmico','direction'=>'conversacional, ágil e simpático, com variação de entonação e naturalidade de conteúdo nativo para redes sociais']; return ['id'=>'conversacional','label'=>'Conversacional','direction'=>'jornalístico porém próximo, conversacional e natural, evitando rigidez de telejornal tradicional']; }\nfunction rpia_human_voice_id(){ return 'cbdcad7a79e44262b4f4dad0a1b1fba9'; }",
'Humanization helpers');

$old="  \$isBoletim=!empty(\$job['boletim']); \$presenter=tvs_clean_text(\$job['presenter_name']??''); \$tone=tvs_clean_text(\$job['presenter_tone']??'');\n  if(\$isBoletim){ if(\$presenter==='') \$presenter='apresentador digital dos boletins da TV Sumaré'; if(\$tone==='') \$tone='informal, próximo, ágil e confiável'; \$presentation=\"Persona: {\$presenter}. Tom: {\$tone}. Apresente como conteúdo nativo de redes sociais: natural, direto, simpático e conversacional, sem perder precisão jornalística. Evite postura rígida de telejornal e linguagem excessivamente formal.\"; }\n  else \$presentation=\"Tom: apresentador de telejornal regional, claro, confiável, objetivo e sem sensacionalismo.\";\n  return \"Crie um vídeo jornalístico regional para a TV Sumaré, portal regional de notícias de Sumaré e Região Metropolitana de Campinas.\\n\\nFormato: {\$orientation}. Duração alvo: {\$durationTarget}. {\$presentation}\\n\\nUse o avatar e a voz fornecidos na configuração deste vídeo. Use identidade visual limpa e moderna. Inclua legendas e cards discretos de apoio.\\n\\nTítulo da pauta: {\$title}\\nCidade/região: {\$city}\\nFonte: {\$source}\\n\\nTexto falado obrigatório, sem inventar dados além deste roteiro:\\n{\$script}\\n\\nRegras editoriais: não cite que o conteúdo foi gerado por IA; não acrescente números, datas, nomes ou acusações que não estejam no roteiro; preserve a informação jornalística; finalize reforçando que o público acompanhe a TV Sumaré.\";";
$new="  \$isBoletim=!empty(\$job['boletim']); \$presenter=tvs_clean_text(\$job['presenter_name']??''); \$tone=tvs_clean_text(\$job['presenter_tone']??''); \$profile=rpia_presentation_profile(\$job);\n  if(\$isBoletim){ if(\$presenter==='') \$presenter='apresentador digital dos boletins da TV Sumaré'; if(\$tone==='') \$tone='informal, próximo, ágil e confiável'; \$presentation=\"Persona: {\$presenter}. Tom-base: {\$tone}. Perfil de apresentação escolhido automaticamente: {\$profile['label']}. Direção: {\$profile['direction']}.\"; }\n  else \$presentation=\"Perfil de apresentação escolhido automaticamente: {\$profile['label']}. Direção: {\$profile['direction']}.\";\n  return \"Crie um vídeo jornalístico regional fotorealista para a TV Sumaré, portal regional de notícias de Sumaré e Região Metropolitana de Campinas.\\n\\nFormato: {\$orientation}. Duração alvo: {\$durationTarget}. {\$presentation}\\n\\nDIREÇÃO HUMANA OBRIGATÓRIA: aparência fotorealista; contato visual natural com a câmera; sincronização labial precisa; piscadas naturais; microexpressões faciais sutis; pequenos movimentos espontâneos de cabeça e postura; gestos discretos e não repetitivos quando disponíveis; respiração e pausas naturais; variação de ritmo, entonação e ênfase. Evite rosto congelado, sorriso permanente, balanço repetitivo, gesticulação exagerada, leitura monótona, cadência robótica ou postura rígida. O resultado deve parecer uma apresentação humana profissional, não uma demonstração de avatar.\\n\\nVOZ: use a voz configurada para o vídeo, com prosódia brasileira natural, pausas lógicas, variação de entonação e ênfase jornalística sem teatralização.\\n\\nUse identidade visual limpa e moderna. Inclua legendas e cards discretos de apoio quando apropriado.\\n\\nTítulo da pauta: {\$title}\\nCidade/região: {\$city}\\nFonte: {\$source}\\n\\nTexto falado obrigatório, sem inventar dados além deste roteiro:\\n{\$script}\\n\\nRegras editoriais: não cite que o conteúdo foi gerado por IA; não acrescente números, datas, nomes ou acusações que não estejam no roteiro; preserve a informação jornalística; finalize reforçando que o público acompanhe a TV Sumaré.\";";
hum_patch($code,$old,$new,'Humanized Video Agent prompt');

$old="  foreach(['avatar_id'=>'heygen_avatar_id','voice_id'=>'heygen_voice_id','style_id'=>'heygen_style_id','brand_kit_id'=>'heygen_brand_kit_id'] as \$api=>\$local){ \$jobValue=trim((string)(\$job[\$local]??'')); \$cfgValue=trim((string)(\$cfg[\$local]??'')); \$v=\$jobValue!==''?\$jobValue:\$cfgValue; if(\$v!=='') \$payload[\$api]=\$v; }";
$new="  foreach(['avatar_id'=>'heygen_avatar_id','voice_id'=>'heygen_voice_id','style_id'=>'heygen_style_id','brand_kit_id'=>'heygen_brand_kit_id'] as \$api=>\$local){ \$jobValue=trim((string)(\$job[\$local]??'')); \$cfgValue=trim((string)(\$cfg[\$local]??'')); \$v=\$jobValue!==''?\$jobValue:\$cfgValue; if(\$api==='voice_id') \$v=rpia_human_voice_id(); if(\$v!=='') \$payload[\$api]=\$v; } \$payload['metadata']=['presentation_profile'=>rpia_presentation_profile(\$job)['id'],'humanization'=>'enterprise_v1'];";
hum_patch($code,$old,$new,'Preferred human voice');

if(file_put_contents($reporter,$code)===false){fwrite(STDERR,"Falha ao gravar Reporter IA\n");exit(3);} echo "REPORTER_HUMANIZATION_APPLIED=SIM\n";
