<?php
$path='/var/www/html/admin/tvplay.php';
$c=file_get_contents($path); if($c===false){fwrite(STDERR,"tvplay.php ausente\n");exit(1);}
$needle="require_once dirname(__DIR__).'/includes/video_ai_helper.php';";
$replacement=$needle."\nrequire_once dirname(__DIR__).'/includes/youtube_oauth.php';";
if(strpos($c,"require_once dirname(__DIR__).'/includes/youtube_oauth.php';")===false){ if(substr_count($c,$needle)!==1){fwrite(STDERR,"YOUTUBE_INTEGRATION require count inválido\n");exit(2);} $c=str_replace($needle,$replacement,$c); }
$needle="if(isset(\$_GET['msg'])) \$msg=(string)\$_GET['msg']; if(isset(\$_GET['err'])) \$err=(string)\$_GET['err'];";
$replacement=$needle."\nif(isset(\$_GET['yt_msg'])) \$msg=(string)\$_GET['yt_msg']; if(isset(\$_GET['yt_err'])) \$err=(string)\$_GET['yt_err'];";
if(strpos($c,"if(isset(\$_GET['yt_msg']))")===false){ if(substr_count($c,$needle)!==1){fwrite(STDERR,"YOUTUBE_INTEGRATION query count inválido\n");exit(3);} $c=str_replace($needle,$replacement,$c); }
$needle="  if(\$action==='publish_video'){";
$block="  if(\$action==='publish_youtube'){\n    \$idx=null; \$jobs=null; \$job=tvp_find_job(\$_POST['job_id']??'',\$jobs,\$idx);\n    if(!\$job) tvp_admin_redirect(['err'=>'Job não encontrado.']);\n    if(!in_array((string)(\$job['status']??''),['pronto','publicado'],true)) tvp_admin_redirect(['err'=>'O vídeo precisa estar pronto e aprovado antes do envio ao YouTube.']);\n    \$r=tvs_youtube_upload_branded(\$job);\n    if(empty(\$r['ok'])) tvp_admin_redirect(['err'=>\$r['error']??'Falha ao publicar no YouTube.']);\n    \$jobs[\$idx]['youtube_video_id']=\$r['youtube_video_id']??''; \$jobs[\$idx]['youtube_url']=\$r['url']??''; \$jobs[\$idx]['youtube_status']='publicado'; \$jobs[\$idx]['youtube_published_at']=date('c'); \$jobs[\$idx]['updated_at']=date('c'); tvp_save_video_jobs(\$jobs);\n    tvp_admin_redirect(['msg'=>'Vídeo publicado no canal oficial da TV Sumaré no YouTube.']);\n  }\n".$needle;
if(strpos($c,"if(\$action==='publish_youtube')")===false){ if(substr_count($c,$needle)!==1){fwrite(STDERR,"YOUTUBE_INTEGRATION publish hook count inválido\n");exit(4);} $c=str_replace($needle,$block,$c); }
$needle="<section class=\"box\" style=\"margin-top:16px\"><h2>Produção Inteligente</h2>";
$yt="<section class=\"box\" style=\"margin-top:16px\"><h2>Canal oficial no YouTube</h2><p class=\"muted\">Publicação direta após aprovação editorial. O vídeo recebe a marca d’água obrigatória antes do upload.</p><?php if(!tvs_youtube_oauth_ready()): ?><div class=\"notice error\">Defina YOUTUBE_CLIENT_ID e YOUTUBE_CLIENT_SECRET no ambiente da TV Sumaré.</div><?php elseif(tvs_youtube_oauth_connected()): ?><div class=\"notice\">Canal autorizado para upload.</div><?php else: ?><a class=\"btn secondary\" href=\"<?=tvp_h(tvs_youtube_oauth_auth_url())?>\">Autorizar canal @tvsumare</a><?php endif; ?></section>\n".$needle;
if(strpos($c,'<h2>Canal oficial no YouTube</h2>')===false){ if(substr_count($c,$needle)!==1){fwrite(STDERR,"YOUTUBE_INTEGRATION UI hook count inválido\n");exit(5);} $c=str_replace($needle,$yt,$c); }
$needle='<a class="btn secondary" target="_blank" href="<?=tvp_h(($j[\'captioned_video_url\']??\'\')?:($j[\'video_url\']??\'\'))?>">Abrir vídeo</a>';
$replacement=$needle."<?php if(in_array(\$status,['pronto','publicado'],true)): ?><?php if(!empty(\$j['youtube_video_id'])): ?><a class=\"btn secondary\" target=\"_blank\" href=\"<?=tvp_h(\$j['youtube_url']??('https://www.youtube.com/watch?v='.\$j['youtube_video_id']))?>\">Abrir no YouTube</a><?php elseif(tvs_youtube_oauth_connected()): ?><form method=\"post\" style=\"display:inline\" onsubmit=\"return confirm('Publicar este vídeo no canal oficial @tvsumare?');\"><?=tvs_csrf_field()?><input type=\"hidden\" name=\"action\" value=\"publish_youtube\"><input type=\"hidden\" name=\"job_id\" value=\"<?=tvp_h(\$j['id'])?>\"><button class=\"btn secondary\">Publicar no YouTube</button></form><?php endif; ?><?php endif; ?>";
if(strpos($c,'value="publish_youtube"')===false){ if(substr_count($c,$needle)!==1){fwrite(STDERR,"YOUTUBE_INTEGRATION job action count inválido\n");exit(6);} $c=str_replace($needle,$replacement,$c); }
if(file_put_contents($path,$c)===false){fwrite(STDERR,"Falha ao gravar tvplay.php\n");exit(7);} echo "YOUTUBE_PUBLISHING_INTEGRATION_APPLIED=SIM\n";
