<?php
require_once __DIR__.'/outbound_guard.php';
require_once __DIR__.'/video_branding.php';

if (!function_exists('tvs_youtube_oauth_config')) {
  function tvs_youtube_oauth_config(){
    return [
      'client_id'=>trim((string)(getenv('YOUTUBE_CLIENT_ID')?:'')),
      'client_secret'=>trim((string)(getenv('YOUTUBE_CLIENT_SECRET')?:'')),
      'privacy'=>in_array((string)(getenv('YOUTUBE_PRIVACY_STATUS')?:'public'),['public','unlisted','private'],true)?(string)(getenv('YOUTUBE_PRIVACY_STATUS')?:'public'):'public',
    ];
  }
  function tvs_youtube_oauth_path(){ return dirname(__DIR__).'/data/youtube_oauth.json'; }
  function tvs_youtube_oauth_read(){ $p=tvs_youtube_oauth_path(); if(!is_file($p)) return []; $d=json_decode((string)file_get_contents($p),true); return is_array($d)?$d:[]; }
  function tvs_youtube_oauth_write($data){ $p=tvs_youtube_oauth_path(); if(!is_dir(dirname($p))) @mkdir(dirname($p),0775,true); $ok=file_put_contents($p,json_encode($data,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),LOCK_EX)!==false; if($ok) @chmod($p,0600); return $ok; }
  function tvs_youtube_redirect_uri(){ $base=rtrim((string)($GLOBALS['site_url']??getenv('TVSUMARE_SITE_URL')?:''),'/'); return $base.'/admin/youtube-oauth-callback.php'; }
  function tvs_youtube_oauth_ready(){ $c=tvs_youtube_oauth_config(); return $c['client_id']!=='' && $c['client_secret']!==''; }
  function tvs_youtube_oauth_connected(){ $t=tvs_youtube_oauth_read(); return trim((string)($t['refresh_token']??''))!=='' || (trim((string)($t['access_token']??''))!=='' && (int)($t['expires_at']??0)>time()+60); }
  function tvs_youtube_oauth_state(){ $t=tvs_youtube_oauth_read(); $state=bin2hex(random_bytes(24)); $t['oauth_state_hash']=hash('sha256',$state); $t['oauth_state_created_at']=time(); tvs_youtube_oauth_write($t); return $state; }
  function tvs_youtube_oauth_auth_url(){ $c=tvs_youtube_oauth_config(); if($c['client_id']==='') return ''; $q=http_build_query(['client_id'=>$c['client_id'],'redirect_uri'=>tvs_youtube_redirect_uri(),'response_type'=>'code','scope'=>'https://www.googleapis.com/auth/youtube.upload','access_type'=>'offline','prompt'=>'consent','include_granted_scopes'=>'true','state'=>tvs_youtube_oauth_state()]); return 'https://accounts.google.com/o/oauth2/v2/auth?'.$q; }
  function tvs_youtube_http_form($url,$fields,$timeout=30){ if(!function_exists('curl_init')) return ['ok'=>false,'error'=>'cURL indisponível.']; $opts=tvs_outbound_curl_options($url,$timeout); if($opts===null) return ['ok'=>false,'error'=>'Saída HTTP bloqueada.']; $ch=curl_init($url); curl_setopt_array($ch,$opts+[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>http_build_query($fields),CURLOPT_HTTPHEADER=>['Content-Type: application/x-www-form-urlencoded']]); $body=curl_exec($ch); $err=curl_error($ch); $http=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE); curl_close($ch); $j=is_string($body)?json_decode($body,true):null; if($http<200||$http>=300||!is_array($j)) return ['ok'=>false,'http'=>$http,'error'=>'OAuth HTTP '.$http.': '.substr((string)$body,0,500).' '.$err]; return ['ok'=>true,'data'=>$j]; }
  function tvs_youtube_oauth_exchange($code,$state){
    $saved=tvs_youtube_oauth_read(); $hash=(string)($saved['oauth_state_hash']??''); $created=(int)($saved['oauth_state_created_at']??0); if($hash==='' || !hash_equals($hash,hash('sha256',(string)$state)) || $created<time()-900) return ['ok'=>false,'error'=>'Estado OAuth inválido ou expirado.'];
    $c=tvs_youtube_oauth_config(); $r=tvs_youtube_http_form('https://oauth2.googleapis.com/token',['code'=>$code,'client_id'=>$c['client_id'],'client_secret'=>$c['client_secret'],'redirect_uri'=>tvs_youtube_redirect_uri(),'grant_type'=>'authorization_code']); if(empty($r['ok'])) return $r;
    $d=$r['data']; $saved['access_token']=$d['access_token']??''; if(!empty($d['refresh_token'])) $saved['refresh_token']=$d['refresh_token']; $saved['token_type']=$d['token_type']??'Bearer'; $saved['scope']=$d['scope']??''; $saved['expires_at']=time()+(int)($d['expires_in']??3600)-60; unset($saved['oauth_state_hash'],$saved['oauth_state_created_at']);
    if(!tvs_youtube_oauth_write($saved)) return ['ok'=>false,'error'=>'OAuth concluído, mas não foi possível persistir o token do YouTube.'];
    if(trim((string)($saved['access_token']??''))==='') return ['ok'=>false,'error'=>'Google não retornou access_token para o YouTube.'];
    return ['ok'=>true,'has_refresh_token'=>trim((string)($saved['refresh_token']??''))!==''];
  }
  function tvs_youtube_access_token(){
    $saved=tvs_youtube_oauth_read(); if(trim((string)($saved['access_token']??''))!=='' && (int)($saved['expires_at']??0)>time()+60) return ['ok'=>true,'access_token'=>$saved['access_token']];
    $refresh=trim((string)($saved['refresh_token']??'')); if($refresh==='') return ['ok'=>false,'error'=>'Canal YouTube ainda não autorizado.']; $c=tvs_youtube_oauth_config(); $r=tvs_youtube_http_form('https://oauth2.googleapis.com/token',['client_id'=>$c['client_id'],'client_secret'=>$c['client_secret'],'refresh_token'=>$refresh,'grant_type'=>'refresh_token']); if(empty($r['ok'])) return $r; $d=$r['data']; $saved['access_token']=$d['access_token']??''; $saved['expires_at']=time()+(int)($d['expires_in']??3600)-60; tvs_youtube_oauth_write($saved); return ['ok'=>true,'access_token'=>$saved['access_token']];
  }
  function tvs_youtube_upload_branded($job){
    $existing=trim((string)($job['youtube_video_id']??'')); if($existing!=='') return ['ok'=>true,'youtube_video_id'=>$existing,'already_uploaded'=>true,'url'=>'https://www.youtube.com/watch?v='.$existing];
    $source=trim((string)(($job['captioned_video_url']??'')?:($job['video_url']??''))); if($source==='') return ['ok'=>false,'error'=>'Vídeo pronto não encontrado para upload.'];
    $brand=tvs_video_branding_apply($source,$job['id']??'youtube'); if(empty($brand['ok'])) return ['ok'=>false,'error'=>'Marca d’água obrigatória: '.($brand['error']??'falha')]; $path=(string)($brand['path']??''); if(!is_file($path)) return ['ok'=>false,'error'=>'Arquivo marcado não encontrado no servidor.'];
    $tok=tvs_youtube_access_token(); if(empty($tok['ok'])) return $tok; $access=$tok['access_token']; $c=tvs_youtube_oauth_config();
    $title=trim((string)($job['title']??'TV Sumaré')); if(function_exists('mb_substr')) $title=mb_substr($title,0,100,'UTF-8'); else $title=substr($title,0,100);
    $desc=trim((string)($job['youtube_description']??($job['script']??''))); if($desc==='') $desc='TV Sumaré — notícias de Sumaré e Região Metropolitana de Campinas.\n\nAcompanhe: https://tvsumare.com.br'; if(function_exists('mb_substr')) $desc=mb_substr($desc,0,4500,'UTF-8'); else $desc=substr($desc,0,4500);
    $meta=['snippet'=>['title'=>$title,'description'=>$desc,'categoryId'=>'25'],'status'=>['privacyStatus'=>$c['privacy'],'selfDeclaredMadeForKids'=>false]];
    $initUrl='https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status'; $opts=tvs_outbound_curl_options($initUrl,40); if($opts===null) return ['ok'=>false,'error'=>'Upload YouTube bloqueado pela política de saída.']; $size=(int)filesize($path); $ch=curl_init($initUrl); $headers=[]; curl_setopt_array($ch,$opts+[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>json_encode($meta,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$access,'Content-Type: application/json; charset=UTF-8','X-Upload-Content-Length: '.$size,'X-Upload-Content-Type: video/mp4'],CURLOPT_HEADERFUNCTION=>function($ch,$line)use(&$headers){ $len=strlen($line); $p=strpos($line,':'); if($p!==false) $headers[strtolower(trim(substr($line,0,$p)))]=trim(substr($line,$p+1)); return $len; }]); $body=curl_exec($ch); $http=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE); $err=curl_error($ch); curl_close($ch); $location=$headers['location']??''; if($http<200||$http>=300||$location==='') return ['ok'=>false,'error'=>'Falha ao iniciar upload YouTube HTTP '.$http.': '.substr((string)$body,0,500).' '.$err];
    $fp=fopen($path,'rb'); if(!$fp) return ['ok'=>false,'error'=>'Não foi possível abrir o vídeo marcado para upload.']; $opts=tvs_outbound_curl_options($location,600); if($opts===null){fclose($fp);return ['ok'=>false,'error'=>'URL resumível do YouTube bloqueada.'];} $ch=curl_init($location); curl_setopt_array($ch,$opts+[CURLOPT_RETURNTRANSFER=>true,CURLOPT_UPLOAD=>true,CURLOPT_INFILE=>$fp,CURLOPT_INFILESIZE=>$size,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$access,'Content-Type: video/mp4','Content-Length: '.$size]]); $body=curl_exec($ch); $http=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE); $err=curl_error($ch); curl_close($ch); fclose($fp); $j=is_string($body)?json_decode($body,true):null; if($http<200||$http>=300||!is_array($j)||empty($j['id'])) return ['ok'=>false,'error'=>'Upload YouTube falhou HTTP '.$http.': '.substr((string)$body,0,700).' '.$err]; return ['ok'=>true,'youtube_video_id'=>$j['id'],'url'=>'https://www.youtube.com/watch?v='.$j['id'],'privacy_status'=>$j['status']['privacyStatus']??$c['privacy'],'branded_url'=>$brand['url']??''];
  }
}